import asyncio
import json
from src.retrieval.retriever import HierarchicalRetriever
from src.storage.qdrant_store import get_client, get_embedder
from src.workflows.legal_graph import legal_graph, get_retriever

async def trace_query():
    # Let's trace it without doc_id first to see what the global response is, 
    # but also with PelicanDelivers doc_id to match the user's screenshot.
    doc_id = "d1f9c3db-6c0d-4bc4-879d-a93c9e01c323"
    question = "What is the termination date?"
    
    # We will simulate the `rag.ask` call manually to capture step by step.
    state = {"question": question, "selected_doc_ids": [doc_id], "chat_history": None}
    
    # Step 1: retrieve_node
    from src.workflows.legal_graph import retrieve_node, generate_node, citation_node
    state1 = retrieve_node(state)
    state.update(state1)
    
    with open("pipeline_trace.txt", "w") as f:
        f.write("=== STEP 1: Final sentence chunks returned by retriever ===\n")
        for chunk in state.get("retrieved_chunks", []):
            f.write(f"ChunkID: {chunk.chunk_id}\nPage: {chunk.page_num}\nHeading: {chunk.heading}\nScore: {chunk.score}\nPreview: {chunk.text[:150]}\n\n")
            
        f.write("\n=== STEP 2: Exact input entering citation_node ===\n")
        # generate_node runs first
        state2 = generate_node(state)
        state.update(state2)
        
        f.write("Answer generated:\n")
        f.write(state.get("answer", "") + "\n\n")
        f.write("retrieved_chunks passed to citation_node:\n")
        for chunk in state.get("retrieved_chunks", []):
            f.write(f"  - Chunk: {chunk.chunk_id}, Page: {chunk.page_num}, Heading: {chunk.heading}\n")
            
        f.write("\n=== STEP 3: Exact citations generated by citation_node ===\n")
        state3 = citation_node(state)
        state.update(state3)
        citations = state.get("citations", [])
        for c in citations:
            f.write(f"Page: {c.get('page')}, Heading: {c.get('section')}, Document: {c.get('document')}\n")
            
        f.write("\n=== STEP 4: Exact JSON returned to frontend ===\n")
        from src.models.responses import QueryResponse
        response = {
            "answer": state.get("answer", ""),
            "citations": state.get("citations", []),
            "model_used": state.get("model_used")
        }
        f.write(json.dumps(response, indent=2))
        
        f.write("\n=== SUMMARY AND DEDUPLICATION ANALYSIS ===\n")
        f.write(f"Number of retrieved chunks: {len(state.get('retrieved_chunks', []))}\n")
        f.write(f"Number of generated citations: {len(citations)}\n")

if __name__ == "__main__":
    asyncio.run(trace_query())
